#!/usr/bin/env python3
"""Generate C++ stub implementations for undefined at::native::* symbols.

Reads undefined symbols from libtorch_hip.dylib and generates a .cpp file
where each function stub throws "not implemented on Hagane/Metal" and each
data symbol (DispatchStub instances) is allocated as zeroed storage.

Symbols already defined in libtorch_cpu.dylib are excluded — they will be
resolved at load time via dynamic linking.

Usage:
    python tools/hagane_gen_stubs.py build/lib/libtorch_hip.dylib \
        --cpu-lib build/lib/libtorch_cpu.dylib \
        -o build/aten/src/ATen/HaganeKernelStubs.cpp
"""

import argparse
import subprocess
import sys
from pathlib import Path


def get_defined_symbols(dylib_path: str) -> set[str]:
    """Return set of mangled symbol names defined (exported) in a dylib."""
    result = subprocess.run(
        ["nm", "-gU", dylib_path], capture_output=True, text=True, check=True
    )
    symbols = set()
    for line in result.stdout.splitlines():
        parts = line.strip().split()
        if len(parts) >= 3:
            symbols.add(parts[2])
    return symbols


def get_undefined_native_symbols(
    dylib_path: str, cpu_defined: set[str] | None = None
) -> list[tuple[str, str]]:
    """Return (mangled, demangled) pairs for undefined symbols from excluded kernel files.

    Catches at::native::*, at::hip::detail::*, and at::cuda::* — anything that
    lives in excluded .hip sources rather than in libtorch_cpu or hagane-sdk libs.
    """
    result = subprocess.run(
        ["nm", "-u", dylib_path], capture_output=True, text=True, check=True
    )
    mangled = []
    for line in result.stdout.splitlines():
        sym = line.strip()
        if not sym:
            continue
        mangled.append(sym)

    # Demangle all at once
    demangle = subprocess.run(
        ["c++filt"], input="\n".join(mangled), capture_output=True, text=True, check=True
    )
    demangled = demangle.stdout.splitlines()

    # Namespaces that contain symbols from excluded .hip kernel files.
    # Use 'in' not 'startswith' because template instantiations have return types
    # prepended (e.g., "void at::native::foo<float>(...)")
    STUB_PATTERNS = ("at::native::", "at::hip::detail::", "at::cuda::jit::")

    # Symbols with real implementations in HaganeOps.cpp — do not stub these.
    HAGANE_IMPLEMENTED = (
        "at::native::empty_cuda(",
        "at::native::empty_strided_cuda(",
        "at::native::structured_ufunc_add_CUDA::impl(",
        "at::native::GeluCUDAKernelImpl(",
        "at::native::GeluBackwardCUDAKernelImpl(",
    )

    if cpu_defined is None:
        cpu_defined = set()

    pairs = []
    skipped_cpu = 0
    for m, d in zip(mangled, demangled):
        if any(pat in d for pat in STUB_PATTERNS):
            if any(impl in d for impl in HAGANE_IMPLEMENTED):
                continue
            # Skip symbols defined in libtorch_cpu — resolved at load time
            if m in cpu_defined:
                skipped_cpu += 1
                continue
            pairs.append((m, d))

    if skipped_cpu:
        print(f"  Skipped {skipped_cpu} symbols (defined in libtorch_cpu)")
    return pairs


def classify_symbols(
    pairs: list[tuple[str, str]],
) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    """Split into (functions, data) based on demangled signature."""
    functions = []
    data = []
    for mangled, demangled in pairs:
        # Functions have a closing paren (possibly followed by qualifiers like const)
        # Data symbols don't have parentheses at all, OR have them only inside template args
        # Heuristic: if ')' appears AND is after the last '>' (or there's no '>'), it's a function
        last_paren = demangled.rfind(")")
        last_angle = demangled.rfind(">")
        if last_paren > last_angle:
            functions.append((mangled, demangled))
        else:
            data.append((mangled, demangled))
    return functions, data


def extract_function_name(demangled: str) -> str:
    """Extract a short readable name from demangled symbol for error messages."""
    # e.g. "at::native::foo_cuda(at::Tensor const&)" -> "foo_cuda"
    paren = demangled.find("(")
    if paren == -1:
        name = demangled
    else:
        name = demangled[:paren]
    # Take last component after ::
    parts = name.split("::")
    return parts[-1] if parts else name


def generate_cpp(
    functions: list[tuple[str, str]],
    data: list[tuple[str, str]],
) -> str:
    lines = []
    lines.append("// Auto-generated by tools/hagane_gen_stubs.py")
    lines.append("// Stub implementations for at::native::* symbols from excluded .hip kernel files.")
    lines.append("// Each function throws 'not implemented on Hagane/Metal' at runtime.")
    lines.append("")
    lines.append('#if defined(__HIP_PLATFORM_HAGANE__)')
    lines.append("")
    lines.append("#include <stdexcept>")
    lines.append("#include <string>")
    lines.append("")
    lines.append("// Use a plain throw to avoid pulling in TORCH_CHECK dependencies")
    lines.append("// that might create circular includes.")
    lines.append('#define HAGANE_STUB(name) \\')
    lines.append('    throw std::runtime_error( \\')
    lines.append('        std::string(name) + " is not implemented on Hagane/Metal")')
    lines.append("")

    # Function stubs: use __asm__ label to force the mangled name
    lines.append("// ---- Function stubs ({} symbols) ----".format(len(functions)))
    lines.append("")
    for i, (mangled, demangled) in enumerate(functions):
        fname = extract_function_name(demangled)
        # __asm__ label forces the compiler to emit this symbol with the given mangled name.
        # We declare as void since TORCH_CHECK throws before returning — return type
        # is not part of C++ name mangling for non-template functions.
        lines.append(
            f'__attribute__((visibility("default"))) extern "C" void _hagane_stub_{i}() __asm__("{mangled}");'
        )
        lines.append(f"void _hagane_stub_{i}() {{ HAGANE_STUB(\"{fname}\"); }}")
        lines.append("")

    # Data stubs: allocate zeroed storage with the right symbol name
    lines.append("// ---- Data stubs ({} symbols) ----".format(len(data)))
    lines.append("// DispatchStub instances and static members — zeroed storage.")
    lines.append("")
    for i, (mangled, demangled) in enumerate(data):
        # 256 bytes is generous for DispatchStub (typically ~64 bytes on ARM64)
        lines.append(
            f'__attribute__((visibility("default"))) extern "C" char _hagane_data_{i}[256] __asm__("{mangled}");'
        )
        lines.append(f"char _hagane_data_{i}[256] = {{}};")
        lines.append("")

    lines.append("#endif // __HIP_PLATFORM_HAGANE__")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dylib", help="Path to libtorch_hip.dylib")
    parser.add_argument("--cpu-lib", help="Path to libtorch_cpu.dylib (exclude its symbols)")
    parser.add_argument("-o", "--output", required=True, help="Output .cpp path")
    args = parser.parse_args()

    cpu_defined = None
    if args.cpu_lib:
        print(f"Reading defined symbols from {args.cpu_lib}...")
        cpu_defined = get_defined_symbols(args.cpu_lib)
        print(f"  {len(cpu_defined)} symbols in libtorch_cpu")

    pairs = get_undefined_native_symbols(args.dylib, cpu_defined)
    print(f"Found {len(pairs)} symbols needing stubs")

    functions, data = classify_symbols(pairs)
    print(f"  Functions: {len(functions)}")
    print(f"  Data:      {len(data)}")

    cpp = generate_cpp(functions, data)

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(cpp)
    print(f"Generated {out} ({len(functions) + len(data)} stubs)")


if __name__ == "__main__":
    main()
